packages:
  - "apps/*"
  - "packages/*"
  - "agents"

minimumReleaseAge: 0

syncInjectedDepsAfterScripts:
  - typecheck
  - test
  - lint
  - fmt

overrides:
  "@ag-ui/client": "0.0.59"
  "@ag-ui/core": "0.0.59"
  "@ag-ui/encoder": "0.0.59"
  "@ag-ui/proto": "0.0.59"
  "@huggingface/transformers>sharp": "0.35.3"
  "@modelcontextprotocol/sdk": "1.30.0"
  "ansi-to-react>linkify-it": "5.0.2"
  "jayson>uuid": "11.1.1"
  "next>postcss": "8.5.25"
  "next>sharp": "0.35.3"
  "react-native-markdown-display>markdown-it": "14.3.0"
  "xcode>uuid": "11.1.1"

allowBuilds:
  "@modelcontextprotocol/ext-apps": true
  "@mongodb-js/zstd": true
  agents-monorepo: true
  "@clerk/shared": true
  "@scarf/scarf": true
  better-sqlite3: true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  core-js-pure: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  onnxruntime-node: false
  protobufjs: true
  dtrace-provider: false
  esbuild: true
  msw: true
  node-liblzma: true
  workerd: true
  highlight.js: true
  "@sentry/cli": false

onlyBuiltDependencies:
  - "agents-monorepo"
  - "@clerk/shared"
  - "better-sqlite3"
  - "browser-tabs-lock"
  - "bufferutil"
  - "core-js"
  - "msgpackr-extract"
  - "sharp"
  - "unrs-resolver"
  - "utf-8-validate"
  - "@scarf/scarf"
  - "protobufjs"
  - "msw"
pmOnFail: ignore
