packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 0

allowBuilds:
  agents-monorepo: true
  "@clerk/shared": true
  "@scarf/scarf": true
  better-sqlite3: true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  onnxruntime-node: false
  protobufjs: true
  dtrace-provider: false
  msw: true

onlyBuiltDependencies:
  - "agents-monorepo"
  - "@clerk/shared"
  - "better-sqlite3"
  - "browser-tabs-lock"
  - "bufferutil"
  - "core-js"
  - "msgpackr-extract"
  - "sharp"
  - "unrs-resolver"
  - "utf-8-validate"
  - "@scarf/scarf"
  - "protobufjs"
  - "msw"
