packages:
  - "apps/*"
  - "packages/*"
  - "agents"

minimumReleaseAge: 0

syncInjectedDepsAfterScripts:
  - typecheck
  - test
  - lint
  - fmt

overrides:
  "@modelcontextprotocol/sdk": "1.30.0"
  ws: "8.20.1"

allowBuilds:
  "@modelcontextprotocol/ext-apps": true
  "@mongodb-js/zstd": true
  agents-monorepo: true
  "@clerk/shared": true
  "@scarf/scarf": true
  better-sqlite3: true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  core-js-pure: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  onnxruntime-node: false
  protobufjs: true
  dtrace-provider: false
  esbuild: true
  msw: true
  node-liblzma: true
  workerd: true
  highlight.js: true

onlyBuiltDependencies:
  - "agents-monorepo"
  - "@clerk/shared"
  - "better-sqlite3"
  - "browser-tabs-lock"
  - "bufferutil"
  - "core-js"
  - "msgpackr-extract"
  - "sharp"
  - "unrs-resolver"
  - "utf-8-validate"
  - "@scarf/scarf"
  - "protobufjs"
  - "msw"
