// Command contracts generates checked-in TypeScript client projections and
// shell route data from the canonical Go catalog and typed Go agent state.
package main

import (
	"bytes"
	"encoding/json/jsontext"
	json "encoding/json/v2"
	"errors"
	"flag"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"

	"github.com/aranlucas/agents/internal/catalog"
	"github.com/aranlucas/agents/internal/common"
	"github.com/aranlucas/agents/internal/expense"
	"github.com/aranlucas/agents/internal/fitness"
	"github.com/aranlucas/agents/internal/fitnessdata"
	"github.com/aranlucas/agents/internal/grocery"
	"github.com/aranlucas/agents/internal/interview"
	"github.com/aranlucas/agents/internal/jobs"
	"github.com/aranlucas/agents/internal/oralboards"
	"github.com/aranlucas/agents/internal/presentation"
	"github.com/aranlucas/agents/internal/research"
	"github.com/aranlucas/agents/internal/spreadsheet"
	"github.com/aranlucas/agents/internal/travel"
	"github.com/aranlucas/agents/internal/trends"
	"github.com/aranlucas/agents/internal/wellness"

	"github.com/google/jsonschema-go/jsonschema"
)

const generatedHeader = "// Code generated by go run ./cmd/contracts; DO NOT EDIT.\n"

type enumDef struct {
	Name   string
	Values []string
}

type fieldDef struct {
	JSONName string
	TSType   string
	Optional bool
}

type objectDef struct {
	Name   string
	GoType reflect.Type
	Fields []fieldDef
}

func main() {
	typescriptOutput := flag.String("typescript-output", "", "optional output path for a TypeScript client projection")
	check := flag.Bool("check", false, "fail when checked-in generated contracts are stale")
	flag.Parse()

	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}
	outputs, err := generatedOutputs()
	if err != nil {
		fatal(err)
	}
	if *typescriptOutput != "" {
		projection, err := generateTypeScript()
		if err != nil {
			fatal(err)
		}
		outputs[*typescriptOutput] = projection
	}
	for relative, content := range outputs {
		path := relative
		if !filepath.IsAbs(path) {
			path = filepath.Join(root, path)
		}
		if *check {
			current, readErr := os.ReadFile(path)
			if readErr != nil {
				fatal(fmt.Errorf("read generated contract %s: %w", relative, readErr))
			}
			if !bytes.Equal(current, content) {
				fatal(fmt.Errorf("generated contract %s is stale; run go run ./cmd/contracts", relative))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func generatedOutputs() (map[string][]byte, error) {
	outputs := map[string][]byte{
		"scripts/generated-agent-routes.sh": generateShellRoutes(),
	}

	schemas, err := generateJSONSchemas()
	if err != nil {
		return nil, err
	}
	maps.Copy(outputs, schemas)
	return outputs, nil
}

func generateJSONSchemas() (map[string][]byte, error) {
	objects := make(map[string]objectDef)
	objectsByType := make(map[reflect.Type]objectDef)
	for _, object := range objectDefinitions() {
		objects[object.Name] = object
		objectsByType[object.GoType] = object
	}
	stateNames := map[string]string{
		"travel": "TripState", "grocery": "GroceryState", "fitness": "FitnessState",
		"wellness": "WellnessState", "expense": "ExpenseState", "oral-boards": "OralBoardsState",
		"trends": "TrendsState", "research": "ResearchState",
		"jobs": "JobsState", "interview": "InterviewState",
		"spreadsheet": "SpreadsheetState", "presentation": "PresentationState",
	}
	outputs := make(map[string][]byte, len(stateNames))
	for _, spec := range catalog.All() {
		object, ok := objects[stateNames[spec.ClientID]]
		if !ok {
			return nil, fmt.Errorf("client state projection is missing for %s", spec.ClientID)
		}
		schema, err := jsonschema.ForType(object.GoType, nil)
		if err != nil {
			return nil, fmt.Errorf("infer %s schema: %w", object.Name, err)
		}
		schema.Schema = "https://json-schema.org/draft/2020-12/schema"
		schema.Title = object.Name
		if err := projectObjectSchema(schema, object, objectsByType); err != nil {
			return nil, err
		}
		encoded, err := json.Marshal(schema, json.Deterministic(true), jsontext.Multiline(true), jsontext.WithIndent("  "))
		if err != nil {
			return nil, fmt.Errorf("encode %s schema: %w", object.Name, err)
		}
		encoded = compactPrimitiveArrays(encoded, 100)
		encoded = append(encoded, '\n')
		path := filepath.Join("api", "contracts", spec.ClientID+".schema.json")
		outputs[path] = encoded
	}
	return outputs, nil
}

// projectObjectSchema applies the same field projection used by the generated
// TypeScript to the schema inferred from Go. jsonschema.ForType correctly
// captures the wire shape, but it cannot know that client projections exclude
// fields or intentionally make nested fields optional.
func projectObjectSchema(schema *jsonschema.Schema, object objectDef, objects map[reflect.Type]objectDef) error {
	allowed := make(map[string]fieldDef, len(object.Fields))
	order := make([]string, 0, len(object.Fields))
	required := make([]string, 0, len(object.Fields))
	for _, field := range object.Fields {
		allowed[field.JSONName] = field
		order = append(order, field.JSONName)
		if !field.Optional {
			required = append(required, field.JSONName)
		}
	}
	for name := range schema.Properties {
		if _, ok := allowed[name]; !ok {
			delete(schema.Properties, name)
		}
	}
	if len(schema.Properties) != len(allowed) {
		return fmt.Errorf("inferred %s schema has %d selected properties, want %d", object.Name, len(schema.Properties), len(allowed))
	}
	schema.PropertyOrder = order
	schema.Required = required

	for _, field := range object.Fields {
		goField, ok := findJSONField(object.GoType, field.JSONName)
		if !ok {
			return fmt.Errorf("contract %s exposes %q, which is absent from Go type %v", object.Name, field.JSONName, object.GoType)
		}
		property := schema.Properties[field.JSONName]
		if property == nil {
			return fmt.Errorf("inferred %s schema is missing property %q", object.Name, field.JSONName)
		}
		if !strings.Contains(field.TSType, " | null") {
			removeNullType(property)
		}
		if err := projectNestedSchema(property, goField.Type, objects); err != nil {
			return fmt.Errorf("project %s.%s schema: %w", object.Name, field.JSONName, err)
		}
		applyTypeScriptConstraint(property, field.TSType)
	}
	return nil
}

func projectNestedSchema(schema *jsonschema.Schema, goType reflect.Type, objects map[reflect.Type]objectDef) error {
	for goType.Kind() == reflect.Pointer {
		goType = goType.Elem()
	}
	if object, ok := objects[goType]; ok {
		return projectObjectSchema(schema, object, objects)
	}
	switch goType.Kind() {
	case reflect.Array, reflect.Slice:
		if schema.Items == nil {
			return errors.New("array schema has no item definition")
		}
		return projectNestedSchema(schema.Items, goType.Elem(), objects)
	default:
		return nil
	}
}

func removeNullType(schema *jsonschema.Schema) {
	if schema.Type == "null" {
		schema.Type = ""
	}
	if len(schema.Types) == 0 {
		return
	}
	types := make([]string, 0, len(schema.Types))
	for _, value := range schema.Types {
		if value != "null" {
			types = append(types, value)
		}
	}
	if len(types) == 1 {
		schema.Type, schema.Types = types[0], nil
		return
	}
	schema.Types = types
}

func applyTypeScriptConstraint(schema *jsonschema.Schema, tsType string) {
	values, ok := typeScriptEnum(tsType)
	if ok {
		schema.Enum = values
	}
}

func typeScriptEnum(tsType string) ([]any, bool) {
	tsType = strings.TrimSpace(tsType)
	if tsType == "" {
		return nil, false
	}
	includeNull := strings.HasSuffix(tsType, " | null")
	tsType = strings.TrimSuffix(tsType, " | null")
	for _, definition := range enumDefinitions() {
		if definition.Name != tsType {
			continue
		}
		values := make([]any, 0, len(definition.Values)+1)
		for _, value := range definition.Values {
			values = append(values, value)
		}
		if includeNull {
			values = append(values, nil)
		}
		return values, true
	}

	parts := strings.Split(tsType, " | ")
	values := make([]any, 0, len(parts)+1)
	for _, part := range parts {
		if strings.HasPrefix(part, `"`) {
			value, err := strconv.Unquote(part)
			if err != nil {
				return nil, false
			}
			values = append(values, value)
			continue
		}
		value, err := strconv.Atoi(part)
		if err != nil {
			return nil, false
		}
		values = append(values, value)
	}
	if includeNull {
		values = append(values, nil)
	}
	return values, len(values) > 0
}

func compactPrimitiveArrays(encoded []byte, width int) []byte {
	lines := strings.Split(string(encoded), "\n")
	result := make([]string, 0, len(lines))
	for index := 0; index < len(lines); {
		line := lines[index]
		trimmed := strings.TrimSpace(line)
		if !strings.HasSuffix(trimmed, "[") {
			result = append(result, line)
			index++
			continue
		}
		end := index + 1
		var values []string
		valid := false
		for ; end < len(lines); end++ {
			value := strings.TrimSpace(lines[end])
			if value == "]" || value == "]," {
				valid = len(values) > 0
				break
			}
			primitive := strings.TrimSuffix(value, ",")
			_, numericErr := strconv.ParseFloat(primitive, 64)
			quoted := strings.HasPrefix(primitive, `"`) && strings.HasSuffix(primitive, `"`)
			if !quoted && primitive != "true" && primitive != "false" && primitive != "null" && numericErr != nil {
				valid = false
				break
			}
			values = append(values, primitive)
		}
		if !valid || end >= len(lines) {
			result = append(result, line)
			index++
			continue
		}
		closing := strings.TrimSpace(lines[end])
		candidate := strings.TrimSuffix(line, "[") + "[" + strings.Join(values, ", ") + "]"
		if strings.HasSuffix(closing, ",") {
			candidate += ","
		}
		if len(candidate) > width {
			result = append(result, lines[index:end+1]...)
		} else {
			result = append(result, candidate)
		}
		index = end + 1
	}
	return []byte(strings.Join(result, "\n"))
}

func generateTypeScript() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(generatedHeader)
	out.WriteString("\nexport const AGENT_ORDER = [\n")
	for _, spec := range catalog.All() {
		fmt.Fprintf(&out, "  %q,\n", spec.ClientID)
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type AgentId = (typeof AGENT_ORDER)[number];\n\n")
	out.WriteString("export const AGENT_BACKEND_PATHS = {\n")
	for _, spec := range catalog.All() {
		fmt.Fprintf(&out, "  %s: %q,\n", typeScriptProperty(spec.ClientID), spec.Route)
	}
	out.WriteString("} as const satisfies Record<AgentId, string>;\n")

	for _, enum := range enumDefinitions() {
		declaration := fmt.Sprintf("export type %s = %s;", enum.Name, quotedUnion(enum.Values))
		if len(declaration) <= 100 {
			fmt.Fprintf(&out, "\n%s\n", declaration)
			continue
		}
		fmt.Fprintf(&out, "\nexport type %s =\n", enum.Name)
		for index, value := range enum.Values {
			separator := ""
			if index == len(enum.Values)-1 {
				separator = ";"
			}
			fmt.Fprintf(&out, "  | %q%s\n", value, separator)
		}
	}
	out.WriteString("\nexport type TrendsCell = string | number | boolean | null;\n")
	out.WriteString("export type TrendsRow = Record<string, TrendsCell>;\n")

	objects := objectDefinitions()
	names := make(map[reflect.Type]string, len(objects))
	for _, object := range objects {
		if prior, exists := names[object.GoType]; exists {
			return nil, fmt.Errorf("go type %v is mapped to both %s and %s", object.GoType, prior, object.Name)
		}
		names[object.GoType] = object.Name
	}
	for _, object := range objects {
		if err := renderObject(&out, object, names); err != nil {
			return nil, err
		}
	}
	return out.Bytes(), nil
}

func renderObject(out *bytes.Buffer, object objectDef, names map[reflect.Type]string) error {
	if object.GoType.Kind() != reflect.Struct {
		return fmt.Errorf("contract %s uses non-struct Go type %v", object.Name, object.GoType)
	}
	fmt.Fprintf(out, "\nexport type %s = {\n", object.Name)
	seen := make(map[string]bool, len(object.Fields))
	for _, field := range object.Fields {
		if seen[field.JSONName] {
			return fmt.Errorf("contract %s repeats field %s", object.Name, field.JSONName)
		}
		seen[field.JSONName] = true
		goField, ok := findJSONField(object.GoType, field.JSONName)
		if !ok {
			return fmt.Errorf("contract %s exposes %q, which is absent from Go type %v", object.Name, field.JSONName, object.GoType)
		}
		tsType := field.TSType
		if tsType == "" {
			var err error
			tsType, err = inferTypeScript(goField.Type, names)
			if err != nil {
				return fmt.Errorf("contract %s field %s: %w", object.Name, field.JSONName, err)
			}
		}
		optional := ""
		if field.Optional {
			optional = "?"
		}
		fmt.Fprintf(out, "  %s%s: %s;\n", field.JSONName, optional, tsType)
	}
	out.WriteString("};\n")
	return nil
}

func findJSONField(goType reflect.Type, name string) (reflect.StructField, bool) {
	for i := range goType.NumField() {
		field := goType.Field(i)
		jsonName, _, _ := strings.Cut(field.Tag.Get("json"), ",")
		if jsonName == "" {
			jsonName = field.Name
		}
		if jsonName == name {
			return field, true
		}
	}
	return reflect.StructField{}, false
}

func inferTypeScript(goType reflect.Type, names map[reflect.Type]string) (string, error) {
	if name, ok := names[goType]; ok {
		return name, nil
	}
	switch goType.Kind() {
	case reflect.Pointer:
		return inferTypeScript(goType.Elem(), names)
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Slice, reflect.Array:
		element, err := inferTypeScript(goType.Elem(), names)
		if err != nil {
			return "", err
		}
		if strings.Contains(element, " | ") {
			element = "(" + element + ")"
		}
		return element + "[]", nil
	case reflect.Map:
		if goType.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %v is not a string", goType.Key())
		}
		value, err := inferTypeScript(goType.Elem(), names)
		if err != nil {
			return "", err
		}
		return "Record<string, " + value + ">", nil
	default:
		return "", fmt.Errorf("unsupported Go type %v", goType)
	}
}

func enumDefinitions() []enumDef {
	return []enumDef{
		{Name: "DocStatus", Values: []string{string(travel.StatusIdle), string(travel.StatusDrafting), string(travel.StatusReadyToBook), string(travel.StatusBooked)}},
		{Name: "TransportMode", Values: []string{string(travel.TransportFlight), string(travel.TransportRoadTrip)}},
		{Name: "FitnessStatus", Values: []string{string(fitness.StatusIdle), string(fitness.StatusSyncing), string(fitness.StatusPlanning), string(fitness.StatusReady)}},
		{Name: "WellnessStatus", Values: []string{string(wellness.StatusIdle), string(wellness.StatusDelegating), string(wellness.StatusPlanning), string(wellness.StatusReady)}},
		{Name: "ExpenseStatus", Values: []string{string(expense.StatusSubmitted), string(expense.StatusAutoApproved), string(expense.StatusNeedsReview), string(expense.StatusApproved), string(expense.StatusRejected)}},
		{Name: "ExpenseRiskLevel", Values: []string{string(expense.RiskLow), string(expense.RiskMedium), string(expense.RiskHigh)}},
		{Name: "ExpenseDeskStatus", Values: []string{"idle", "reviewing", "needs_approval", "ready"}},
		{Name: "OralBoardsPhase", Values: []string{string(oralboards.PhaseIdle), string(oralboards.PhasePresenting), string(oralboards.PhaseQuestioning), string(oralboards.PhaseFeedback), string(oralboards.PhaseComplete)}},
		{Name: "OralBoardsSkill", Values: []string{string(oralboards.SkillRemember), string(oralboards.SkillUnderstandApply), string(oralboards.SkillAnalyzeEvaluate)}},
		{Name: "OralBoardsOutcome", Values: []string{"pass", "borderline", "not_yet"}},
		{Name: "ResearchStatus", Values: []string{string(research.StatusIdle), string(research.StatusDrafting), string(research.StatusReady)}},
		{Name: "PresentationSlideType", Values: []string{"title", "content", "bullets", "two-column"}},
		{Name: "PresentationTheme", Values: []string{"light", "dark", "minimal"}},
		{Name: "PresentationStatus", Values: []string{string(presentation.StatusIdle), string(presentation.StatusDrafting), string(presentation.StatusReady)}},
		{Name: "TrendsStatus", Values: []string{string(trends.StatusIdle), string(trends.StatusQuerying), string(trends.StatusReady), string(trends.StatusEmpty), string(trends.StatusError)}},
		{Name: "JobsStatus", Values: []string{string(jobs.StatusIdle), string(jobs.StatusResearching), string(jobs.StatusMatching), string(jobs.StatusDrafting), string(jobs.StatusReady)}},
		{Name: "JobMatchVerdict", Values: []string{string(jobs.VerdictStrongMatch), string(jobs.VerdictMatch), string(jobs.VerdictStretch), string(jobs.VerdictSkip)}},
		{Name: "JobCandidateStatus", Values: []string{string(jobs.CandidateNew), string(jobs.CandidateShortlisted), string(jobs.CandidateDismissed)}},
		{Name: "InterviewTrack", Values: []string{string(interview.TrackBehavioral), string(interview.TrackCoding)}},
		{Name: "InterviewDifficulty", Values: []string{string(interview.DifficultyEasy), string(interview.DifficultyMedium), string(interview.DifficultyHard)}},
		{Name: "InterviewCoachingStyle", Values: []string{string(interview.StyleInterview), string(interview.StyleGuided)}},
		{Name: "InterviewStatus", Values: []string{string(interview.StatusIdle), string(interview.StatusPracticing), string(interview.StatusFeedback), string(interview.StatusComplete)}},
	}
}

func objectDefinitions() []objectDef {
	return []objectDef{
		object("CartItem", common.CartItem{}, required("name", "quantity"), optional("price", "upc")),
		object("ProductMatch", common.ProductMatch{}, required("query", "name", "upc"), optional("image_url", "price", "size")),
		object("ShoppingPantryItem", grocery.ShoppingPantryItemState{}, required("name", "quantity", "added_at"), optional("expires_at")),
		object("ShoppingEquipmentItem", grocery.ShoppingEquipmentItemState{}, required("name", "added_at"), optional("category")),
		object("ShoppingOrderItem", grocery.ShoppingOrderItemState{}, required("upc", "name", "quantity"), optional("price")),
		object("ShoppingOrder", grocery.ShoppingOrderState{}, required("id", "items", "total_items", "placed_at"), optional("estimated_total", "location_id", "notes")),
		object("ShoppingPreferredStore", grocery.ShoppingPreferredStoreState{}, required("location_id", "name", "address", "chain", "set_at")),
		object("ShoppingFrequentItem", grocery.ShoppingFrequentItemState{}, required("name", "upc", "orders", "total_quantity")),
		object("ShoppingProfile", grocery.ShoppingProfileState{}, required("pantry", "equipment", "recent_orders", "frequent_items"), optional("preferred_store")),
		object("RecipeDraftIngredient", grocery.RecipeDraftIngredient{}, required("name", "quantity", "unit", "note")),
		object("RecipeDraft", grocery.RecipeDraft{}, required("title", "description", "servings", "notes", "ingredients", "steps", "tags")),
		object("FitnessActivity", fitnessdata.Activity{}, required("id", "name"), fields(
			field("source", `"health_connect" | "healthkit" | "strava" | "strava_import"`, true),
			field("sport_type", "", true), field("start_date", "", true), field("end_date", "", true),
			field("distance_m", "", true), field("moving_time_s", "", true), field("elapsed_time_s", "", true),
			field("total_elevation_gain_m", "", true), field("average_heartrate", "", true),
			field("perceived_effort", "", true), field("data_origin", "", true),
		)),
		object("ExpenseItem", expense.Expense{}, required("id", "amount", "submitter", "category", "description", "date"), fields(
			field("status", "ExpenseStatus", false), field("risk_level", "ExpenseRiskLevel | null", true),
			field("risk_summary", "", true), field("recommendation", "", true), field("decision_note", "", true),
		)),
		object("OralBoardsExchange", oralboards.Exchange{}, required("question", "answer", "feedback", "ideal_response"), fields(
			field("skillset", "", true), field("skill", "OralBoardsSkill", true), field("score", "1 | 2 | 3", true),
		)),
		object("OralBoardsSkillsetScore", oralboards.SkillsetScore{}, required("skillset"), fields(
			field("skill", "OralBoardsSkill", true), field("score", "1 | 2 | 3", false), field("rationale", "", false),
		)),
		object("ResearchSection", research.Section{}, required("id", "title", "content")),
		object("ResearchSource", research.Source{}, required("id", "title", "url", "snippet")),
		object("SpreadsheetSheet", spreadsheet.Sheet{}, required("title", "rows")),
		object("PresentationSlide", presentation.Slide{}, fields(
			field("id", "", false), field("type", "PresentationSlideType", false), field("heading", "", false),
			field("body", "", false), field("notes", "", false),
		)),
		object("ApplicationProfile", jobs.ApplicationProfile{}, required(
			"full_name", "email", "phone", "location", "linkedin_url", "github_url", "portfolio_url",
			"work_authorization", "sponsorship", "remote_preference", "relocation", "salary_expectation",
			"voice_notes", "additional_facts",
		)),
		object("ApplicationAnswer", jobs.ApplicationAnswer{}, required("field", "answer", "evidence", "sensitive")),
		object("JobResearchSource", jobs.ResearchSource{}, required("title", "url", "summary")),
		object("JobWatchlist", jobs.JobWatchlist{}, required(
			"roles", "locations", "remote_only", "company_preferences", "must_have", "exclude",
			"minimum_salary_usd", "max_results",
		)),
		object("JobCandidate", jobs.JobCandidate{}, required(
			"id", "title", "company", "location", "url", "posted_at", "compensation", "summary",
			"match_score", "why_match", "concerns", "sources",
		), fields(
			field("match_verdict", "JobMatchVerdict", false),
			field("status", "JobCandidateStatus", false),
		)),
		object("InterviewQuestion", interview.Question{}, required(
			"id", "title", "prompt", "topic", "competency", "examples", "constraints",
		), fields(
			field("track", "InterviewTrack", false),
			field("difficulty", `InterviewDifficulty | ""`, false),
		)),
		object("InterviewRubricScore", interview.RubricScore{}, required("dimension", "score", "evidence")),
		object("InterviewStoryNote", interview.StoryNote{}, required("title", "facts")),
		object("InterviewQuestionFeedback", interview.QuestionFeedback{}, required(
			"question_id", "question_title", "attempt_summary", "rubric", "overall_score", "feedback",
			"strengths", "improvements", "follow_up",
		), fields(field("story_note", "InterviewStoryNote", true))),
		object("TripState", travel.TravelState{}, stateFields(
			field("destination", "", true), field("start_date", "", true), field("end_date", "", true),
			field("travelers", "", true), field("budget_usd", "", true), field("headline", "", true),
			field("summary", "", true), field("itinerary", "", true), field("flights", "", true),
			field("status", "DocStatus", true), field("review_summary", "", true),
		)),
		object("GroceryState", grocery.GroceryState{}, stateFields(
			field("shopping_list", "", true), field("list_title", "", true), field("product_matches", "", true), field("cart", "", true),
			field("shopping_profile", "", true),
			field("meal_plan", "", true), field("recipe", "", true), field("weekly_deals", "", true),
			field("status", `"idle" | "planning" | "ready"`, true), field("notes", "", true),
			field("review_summary", "", true), field("kroger_connected", "", true),
		)),
		object("FitnessState", fitness.FitnessState{}, stateFields(
			field("fitness_data_connected", "", true), field("activity_source", "", true), field("activities", "", true),
			field("activities_synced_at", "", true), field("objective_research", "", true),
			field("training_plan", "", true), field("status", "FitnessStatus", true), field("review_summary", "", true),
		)),
		object("WellnessState", wellness.WellnessState{}, stateFields(
			field("status", "WellnessStatus", true), field("meal_plan", "", true), field("training_plan", "", true),
			field("list_title", "", true), field("recipe", "", true),
			field("shopping_profile", "", true),
			field("weekly_plan", "", true), field("review_summary", "", true), field("kroger_connected", "", true),
			field("fitness_data_connected", "", true), field("activity_source", "", true),
		)),
		object("ExpenseState", expense.ExpenseState{}, stateFields(
			field("expenses", "", true), field("selected_expense_id", "", true), field("expense_report", "", true),
			field("status", "ExpenseDeskStatus", true), field("review_summary", "", true), field("review_threshold_usd", "", true),
		)),
		object("OralBoardsState", oralboards.State{}, stateFields(
			field("case", "", true),
			field("transcript", "", true), field("score_card", "", true), field("score_summary", "", true),
			field("outcome", "OralBoardsOutcome", true), field("status", "OralBoardsPhase", true),
			field("loading_step", "", true), field("interview_complete", "", true), field("active_feedback", "", true),
			field("active_ideal_response", "", true), field("current_question", "", true), field("active_probe", "", true),
		)),
		object("ResearchState", research.ResearchState{}, stateFields(
			field("title", "", true), field("query", "", true), field("report", "", true),
			field("sections", "", true), field("sources", "", true), field("status", "ResearchStatus", true),
			field("review_summary", "", true),
		)),
		object("SpreadsheetState", spreadsheet.SpreadsheetState{}, stateFields(
			field("sheets", "", true), field("active_sheet_index", "", true), field("summary", "", true),
			field("status", `"idle" | "ready"`, true), field("review_summary", "", true),
		)),
		object("PresentationState", presentation.PresentationState{}, stateFields(
			field("title", "", true), field("theme", "PresentationTheme", true), field("slides", "", true),
			field("active_slide_index", "", true), field("status", "PresentationStatus", true), field("review_summary", "", true),
		)),
		object("TrendsState", trends.TrendsState{}, stateFields(
			field("query", "", true), field("generated_sql", "", true), field("columns", "", true),
			field("rows", "TrendsRow[]", true), field("insights", "", true), field("status", "TrendsStatus", true),
			field("error", "", true),
		)),
		object("JobsState", jobs.JobsState{}, stateFields(
			field("profile", "", true), field("watchlist", "", true), field("inbox", "", true),
			field("inbox_refreshed_at", "", true), field("workspace_summary", "", true),
			field("target_title", "", true), field("company", "", true),
			field("job_url", "", true), field("job_description", "", true), field("research_summary", "", true),
			field("sources", "JobResearchSource[]", true), field("match_score", "", true),
			field("match_verdict", "JobMatchVerdict", true), field("match_summary", "", true),
			field("strengths", "", true), field("gaps", "", true), field("tailored_resume", "", true),
			field("application_draft", "", true),
			field("answers", "", true), field("status", "JobsStatus", true), field("review_summary", "", true),
		)),
		object("InterviewState", interview.State{}, stateFields(
			field("track", "InterviewTrack", true), field("target_role", "", true),
			field("target_level", "", true), field("topics", "", true),
			field("difficulty", `InterviewDifficulty | ""`, true),
			field("coaching_style", "InterviewCoachingStyle", true),
			field("target_question_count", "", true),
			field("current_question", "InterviewQuestion | null", true),
			field("active_feedback", "InterviewQuestionFeedback | null", true),
			field("history", "", true), field("hint_level", "", true), field("active_hint", "", true),
			field("completed_count", "", true), field("average_score", "", true),
			field("status", "InterviewStatus", true), field("session_summary", "", true),
			field("next_steps", "", true),
		)),
	}
}

func object(name string, value any, groups ...[]fieldDef) objectDef {
	var result []fieldDef
	for _, group := range groups {
		result = append(result, group...)
	}
	return objectDef{Name: name, GoType: reflect.TypeOf(value), Fields: result}
}

func field(name, tsType string, optional bool) fieldDef {
	return fieldDef{JSONName: name, TSType: tsType, Optional: optional}
}

func fields(values ...fieldDef) []fieldDef { return values }

func required(names ...string) []fieldDef {
	result := make([]fieldDef, 0, len(names))
	for _, name := range names {
		result = append(result, field(name, "", false))
	}
	return result
}

func optional(names ...string) []fieldDef {
	result := make([]fieldDef, 0, len(names))
	for _, name := range names {
		result = append(result, field(name, "", true))
	}
	return result
}

func stateFields(values ...fieldDef) []fieldDef { return values }

func quotedUnion(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, " | ")
}

func typeScriptProperty(value string) string {
	for index, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || r == '$' || (index > 0 && r >= '0' && r <= '9') {
			continue
		}
		return fmt.Sprintf("%q", value)
	}
	return value
}

func generateShellRoutes() []byte {
	var out bytes.Buffer
	out.WriteString("# Code generated by go run ./cmd/contracts; DO NOT EDIT.\n")
	out.WriteString("agent_routes=(")
	for index, spec := range catalog.All() {
		if index > 0 {
			out.WriteByte(' ')
		}
		out.WriteString(spec.Route)
	}
	out.WriteString(")\n")
	return out.Bytes()
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if isDir(filepath.Join(dir, "cmd", "contracts")) && isFile(filepath.Join(dir, "go.mod")) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("repository root not found")
		}
		dir = parent
	}
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func isFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
