from ag_ui_adk import get_a2ui_tool
from agents_shared.state import make_state_initializer
from agents_shared.tools import (
    DEFAULT_RETRY_CONFIG,
    build_model,
    on_model_error_callback,
)
from google.adk.agents import LlmAgent, SequentialAgent
from pydantic import BaseModel, Field

from .prompt import load_agent_instructions
from .tools import (
    begin_trends_query,
    execute_bigquery_sql,
    validate_trends_sql,
    write_trends_result,
)

TRENDS_CATALOG_ID = "https://agents-lucas.vercel.app/a2ui/catalogs/trends/v1"

_TRENDS_A2UI_GUIDELINES = """\
Render a compact Google Trends analysis using the supplied catalog.
Use TrendMetric for summary values, TrendBarChart for ranked categories,
TrendLineChart for time-series data, TrendTable for the source rows, and
SqlDisclosure for generated SQL. Never invent values. Every displayed value
must come from the executed rows, generated SQL, or saved insights. Always
include TrendTable and SqlDisclosure. Do not render empty axes when rows are
empty. Use one stable surface id per result and update that surface only for
presentation-only follow-ups.
"""

_GENERATOR_INSTRUCTION = load_agent_instructions()

_EXECUTOR_INSTRUCTION = """\
You are a Google Trends execution and visualization agent.

The exact BigQuery SQL generated by the prior agent is:

{generated_sql}

Follow these steps in order:
1. Read the latest user message as the original analytical question.
2. Call validate_trends_sql with the exact generated SQL.
3. If validation fails, call write_trends_result with the safe validation error.
   Do not call BigQuery or generate_a2ui.
4. Call begin_trends_query with that question and the validated SQL.
5. Call execute_bigquery_sql with that exact SQL. Never modify it.
6. If execution fails, call write_trends_result with the safe error, then call
   generate_a2ui only if it is available to render a concise error surface.
7. If execution succeeds, derive concise insights only from returned rows.
8. Call write_trends_result with the question, SQL, columns, rows, and insights.
9. Only after write_trends_result succeeds, call generate_a2ui with intent
   "create" and changes describing the saved analysis.
10. Keep chat text to one short completion or fallback sentence.

Never invent values. Never paste raw JSON into chat. Never expose provider
exceptions, credentials, or project details.
"""


class TrendsState(BaseModel):
    query: str = ""
    generated_sql: str = ""
    columns: list[str] = Field(default_factory=list)
    rows: list[dict] = Field(default_factory=list)
    insights: str = ""
    status: str = "idle"
    error: str = ""
    user_id: str = ""


def build_agent() -> SequentialAgent:
    generator = LlmAgent(
        name="TrendsQueryGeneratorAgent",
        model=build_model(),
        retry_config=DEFAULT_RETRY_CONFIG,
        on_model_error_callback=on_model_error_callback,
        static_instruction=_GENERATOR_INSTRUCTION,
        description="Generates bounded BigQuery SQL for Google Trends.",
        output_key="generated_sql",
    )

    executor_model = build_model()
    trends_a2ui_tool = get_a2ui_tool(
        {
            "model": executor_model,
            "guidelines": _TRENDS_A2UI_GUIDELINES,
            "default_surface_id": "trends-result",
            "default_catalog_id": TRENDS_CATALOG_ID,
        }
    )
    executor = LlmAgent(
        name="TrendsQueryExecutorAgent",
        model=executor_model,
        retry_config=DEFAULT_RETRY_CONFIG,
        on_model_error_callback=on_model_error_callback,
        instruction=_EXECUTOR_INSTRUCTION,
        description="Executes Trends SQL, persists rows, and renders A2UI analysis.",
        tools=[
            validate_trends_sql,
            begin_trends_query,
            execute_bigquery_sql,
            write_trends_result,
            trends_a2ui_tool,
        ],
    )

    return SequentialAgent(
        name="GoogleTrendsAgent",
        sub_agents=[generator, executor],
        before_agent_callback=make_state_initializer(TrendsState),
        description="Executes Google Trends analysis and renders structured results.",
    )